const { Model, DataTypes } = require("sequelize");
const { sequelize } = require("../config/database");

class Report extends Model {}

Report.init(
  {
    report_id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    project_id: {
      type: DataTypes.STRING(50),
      allowNull: false,
      references: {
        model: "projects",
        key: "project_id",
      },
    },
    report_type: {
      type: DataTypes.ENUM(
        "project_progress",
        "team_performance",
        "task_deadline",
        "general"
      ),
      allowNull: false,
    },
    report_name: {
      type: DataTypes.STRING(255),
      allowNull: false,
    },
    start_date: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    end_date: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    filters: {
      type: DataTypes.JSON,
      allowNull: true,
      comment: "Additional filters like userId, teamId",
    },
    statistics: {
      type: DataTypes.JSON,
      allowNull: false,
      comment: "Calculated statistics data",
    },
    ai_analysis: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: "AI-generated analysis in Markdown format",
    },
    file_url: {
      type: DataTypes.STRING(500),
      allowNull: true,
      comment: "URL to the saved report file (JSON/PDF)",
    },
    is_auto_generated: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
      comment: "True if generated by scheduled task",
    },
    generated_by: {
      type: DataTypes.STRING(35),
      allowNull: true,
      references: {
        model: "users",
        key: "user_id",
      },
      comment: "User who generated the report (null for auto-generated)",
    },
    created_at: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
  },
  {
    sequelize,
    modelName: "Report",
    tableName: "reports",
    timestamps: false,
  }
);

module.exports = Report;
