-- Create reports table for storing generated reports
CREATE TABLE IF NOT EXISTS reports (
  report_id INT AUTO_INCREMENT PRIMARY KEY,
  project_id VARCHAR(50) NOT NULL,
  report_type ENUM('project_progress', 'team_performance', 'task_deadline', 'general') NOT NULL,
  report_name VARCHAR(255) NOT NULL,
  start_date DATETIME NOT NULL,
  end_date DATETIME NOT NULL,
  filters JSON DEFAULT NULL COMMENT 'Additional filters like userId, teamId',
  statistics JSON NOT NULL COMMENT 'Calculated statistics data',
  ai_analysis TEXT DEFAULT NULL COMMENT 'AI-generated analysis in Markdown format',
  file_url VARCHAR(500) DEFAULT NULL COMMENT 'URL to the saved report file (JSON/PDF)',
  is_auto_generated BOOLEAN DEFAULT FALSE COMMENT 'True if generated by scheduled task',
  generated_by VARCHAR(35) DEFAULT NULL COMMENT 'User who generated the report (null for auto-generated)',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  
  FOREIGN KEY (project_id) REFERENCES projects(project_id) ON DELETE CASCADE,
  FOREIGN KEY (generated_by) REFERENCES users(user_id) ON DELETE SET NULL,
  
  INDEX idx_project_id (project_id),
  INDEX idx_report_type (report_type),
  INDEX idx_created_at (created_at),
  INDEX idx_is_auto_generated (is_auto_generated)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
